export const timeTableInitialData = [
  {"period" : ["I", "II", "III", "IV", "V", "VI","VII", "VIII", "IX"]},
  {"Monday": ["","","","","","","","",""]},
  {"Tuesday": ["","","","","","","","",""]},
  {"Wednesday": ["","","","","","","","",""]},
  {"Thursday": ["","","","","","","","",""]},
  {"Friday": ["","","","","","","","",""]},
  {"Saturday": ["","","","","","","","",""]},
]


//export const timeTableInitialData = [{"period" : ["I", "II", "III", "IV", "V", "VI","VII", "VIII", "IX"]},
//{"Monday":[{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"English","teacher":"Destiny Calderon"}]},{"Tuesday":[{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Maths","teacher":"Jerry Mosley"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Language","teacher":"Destiny Calderon"}]},{"Wednesday":[{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"}]},{"Thursday":[{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Maths","teacher":"Jerry Mosley"}]},{"Friday":[{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Maths","teacher":"Jerry Mosley"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"English","teacher":"Destiny Calderon"}]},{"Saturday":[{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Language","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Science","teacher":"Benjamin Lester"},{"subject":"Maths","teacher":"Jerry Mosley"},{"subject":"English","teacher":"Destiny Calderon"},{"subject":"Language","teacher":"Destiny Calderon"}]}]