export const states = [
  {stateName:"Andhra Pradesh", code:"AP"},
  {stateName:"Arunachal Pradesh", code:"AR"},
  {stateName:"Assam", code:"AS"},
  {stateName:"Bihar", code:"BR"},
  {stateName:"Chhattisgarh", code:"CG"},
  {stateName:"Goa", code:"GA"},
  {stateName:"Gujarat", code:"GJ"},
  {stateName:"Haryana", code:"HR"},
  {stateName:"Himachal Pradesh", code:"HP"},
  {stateName:"Jammu and Kashmir", code:"JK"},
  {stateName:"Jharkhand", code:"JH"},
  {stateName:"Karnataka", code:"KA"},
  {stateName:"Kerala", code:"KL"},
  {stateName:"Madhya Pradesh", code:"MP"},
  {stateName:"Maharashtra", code:"MH"},
  {stateName:"Manipur", code:"MN"},
  {stateName:"Meghalaya", code:"ML"},
  {stateName:"Mizoram", code:"MZ"},
  {stateName:"Nagaland", code:"NL"},
  {stateName:"Orissa", code:"OR"},
  {stateName:"Punjab", code:"PB"},
  {stateName:"Rajasthan", code:"RJ"},
  {stateName:"Sikkim", code:"SK"},
  {stateName:"Tamil Nadu", code:"TN"},
  {stateName:"Tripura", code:"TR"},
  {stateName:"Uttarakhand", code:"UK"},
  {stateName:"Uttar Pradesh", code:"UP"},
  {stateName:"West Bengal", code:"WB"},
  {stateName:"Telangana", code:"TS"},
  {stateName:"Andaman and Nicobar Islands", code:"AN"},
  {stateName:"Chandigarh", code:"CH"},
  {stateName:"Dadra and Nagar Haveli", code:"DH"},
  {stateName:"Daman and Diu", code:"DD"},
  {stateName:"Delhi", code:"DL"},
  {stateName:"Lakshadweep", code:"LD"},
  {stateName:"Pondicherry", code:"PY"}
]